<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/ArrayFunction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Search Array

In [ ]:
import numpy as np

var = np.array([1,2,3,4,2,5,2,5,6,7])
#  index        0,1,2,3,4,5,6,7,8,9

x = np.where( var == 2 )

print(x)

(array([1, 4, 6]),)


In [ ]:
import numpy as np

var = np.array([1,2,3,4,2,5,2,5,6,7])
#  index        0,1,2,3,4,5,6,7,8,9

x = np.where( var/2 == 0 )

print(x)

(array([], dtype=int64),)


In [ ]:
import numpy as np

var = np.array([1,2,3,4,2,5,2,5,6,7])
#  index        0,1,2,3,4,5,6,7,8,9

x = np.where( (var%2) == 0 )

print(x)

(array([1, 3, 4, 6, 8]),)


In [ ]:
# SearchSorted

In [ ]:
var1 = np.array([1,2,3,4,6,7,8,9,10])
#  index         0,1,2,3,4,5,6

x1 = np.searchsorted( var1 , 5,side= "right")

print(x1)

4


In [ ]:
var1 = np.array([1,2,3,4,6,7,8,9,10])
#  index         0,1,2,3,4,5,6

x1 = np.searchsorted( var1 ,[5,6,7],side= "right")

print(x1)

[4 5 6]


In [ ]:
# Sort Array

In [ ]:
var_1 = np.array([4,2,3,1,12,5,22,53,6,7])            # 1D array
#  index        0,1,2,3,4,5,6,7,8,9

print(np.sort(var_1))

[ 1  2  3  4  5  6  7 12 22 53]


In [ ]:
var_2 = np.array(["a","s","d","f"])

print(np.sort(var_2))

['a' 'd' 'f' 's']


In [ ]:
var_1 = np.array([[4,2,3],[1,12,5],[22,53,6,]])            # 2D array


print(np.sort(var_1))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 53]]


In [ ]:
# Filter Array

In [ ]:
var_3 = np.array(["a","s","d","f"])

f = [True,False,True,False]

new_arr = var_3[f]

print(new_arr)

['a' 'd']


In [ ]:
var_3 = np.array(["a","s","d","f"])

f = [True,False,True,False]

new_arr = var_3[f]

print(new_arr)
print(type(new_arr))

['a' 'd']
<class 'numpy.ndarray'>


In [ ]:
# Arithmetic Function

In [ ]:
import numpy as np

var = np.array([1,2,3,4,5])

np.random.shuffle(var)

print(var)

[5 4 2 3 1]


In [ ]:
a = np.array([[1, 2],             # 2D array
              [3, 4],
              [5, 6]])

np.random.shuffle(a)

print(a)

[[5 6]
 [3 4]
 [1 2]]


In [ ]:
# Unique

In [ ]:
var1 = np.array([1,2,3,4,2,5,2,6,2,7])

x = np.unique(var1)

print(x)

[1 2 3 4 5 6 7]


In [ ]:
var1 = np.array([1,2,3,4,2,5,2,6,2,7])

x = np.unique(var1,return_index=True,return_counts=True)

print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9]), array([1, 4, 1, 1, 1, 1, 1]))


In [ ]:
a = np.array(["Python", "Java", "Python", "C++"])

print(np.unique(a))

['C++' 'Java' 'Python']


In [ ]:
a = np.array([1, 2, 2, 3, 3, 3])

values, counts = np.unique(a, return_counts=True)

print(values)
print(counts)

[1 2 3]
[1 2 3]


In [ ]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))

print(y)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.array([1, 2, 3])            # increase size

a.resize(2, 3)

print(a)

[[1 2 3]
 [0 0 0]]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])            # Decreasse size

a.resize(2, 2)

print(a)

[[1 2]
 [3 4]]


In [ ]:
# Flatten

In [ ]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))
print(y)

print(y.flatten)


[[1 2]
 [3 4]
 [5 6]]
<built-in method flatten of numpy.ndarray object at 0x78581e605fb0>


In [ ]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))
print(y)

print(y.flatten(order="C"))

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))
print(y)

print(y.flatten(order="F"))

[[1 2]
 [3 4]
 [5 6]]
[1 3 5 2 4 6]


In [ ]:
a = np.array([[1, 2],
              [3, 4]])

b = a.flatten()

b[0] = 100

print(a)
print(b)

[[1 2]
 [3 4]]
[100   2   3   4]


In [ ]:
# Ravel

In [ ]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))
print(y)

print("Flatten : ",y.flatten(order="C"))
print("Ravel : ",np.ravel(y,order="F"))

[[1 2]
 [3 4]
 [5 6]]
Flatten :  [1 2 3 4 5 6]
Ravel :  [1 3 5 2 4 6]


In [ ]:
a = np.array([[1, 2],
              [3, 4]])

b = a.ravel()

b[0] = 100

print(a)

[[100   2]
 [  3   4]]


In [ ]:
# Insert Array

In [ ]:
import numpy as np

var = np.array([1,2,3,4])

print(var)
print(type(var))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
var = np.array([1,2,3,4])

print(var)

v = np.insert(var, 2, 40)
print(v)

[1 2 3 4]
[ 1  2 40  3  4]


In [ ]:
var = np.array([1,2,3,4])

print(var)

v = np.insert(var, (2,4), 40)
print(v)

[1 2 3 4]
[ 1  2 40  3  4 40]


In [ ]:
var1 = np.array([[1,2,3],[1,22,3]])

v1 = np.insert(var1, 2, 6 )

print(v1)

[ 1  2  6  3  1 22  3]


In [ ]:
var1 = np.array([[1,2,3],[1,22,3]])

v1 = np.insert(var1, 2, 6, axis= 1)

print(v1)

[[ 1  2  6  3]
 [ 1 22  6  3]]


In [ ]:
var1 = np.array([[1,2,3],[1,22,3]])

v1 = np.insert(var1, 2, 6, axis= 0)

print(v1)

[[ 1  2  3]
 [ 1 22  3]
 [ 6  6  6]]


In [ ]:
var1 = np.array([[1,2,3],[1,22,3]])

v1 = np.insert(var1, 2, [22,23,24], axis= 0)

print(v1)

[[ 1  2  3]
 [ 1 22  3]
 [22 23 24]]


In [ ]:
var = np.array([1,2,3,4])

print(var)

# v = np.insert(var, 2, 40)

x = np.append(var,6.5)

print(x)

[1 2 3 4]
[1.  2.  3.  4.  6.5]


In [ ]:
var1 = np.array([[1,2,3],[1,22,3]])

# v1 = np.insert(var1, 2, [22,23,24], axis= 0)

v1 = np.append(var1,[[45,44,23]],axis=0)
print(v1)

[[ 1  2  3]
 [ 1 22  3]
 [45 44 23]]


In [ ]:
# Delete

In [ ]:
import numpy as np

var1 = np.array([1,2,3,4])

print(var1)

d = np.delete(var1,2)

print(d)

[1 2 3 4]
[1 2 4]


In [ ]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

b = np.delete(a, 1, axis=0)

print(b)

[[1 2]
 [5 6]]
