<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Arraylist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

x=[1,2,3,4]

y = np.array(x)
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
l = []

for i in range (1,5):
  int_1 = int(input("enter :"))
  l.append(int_1)

print(np.array(l))

enter :12
enter :13
enter :3
enter :14
[12 13  3 14]


In [ ]:
import numpy as np

x=[1,2,3,4]

y = np.array(x)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [ ]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)


[[1 2 3 4]
 [1 2 3 4]]
2


In [ ]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [ ]:
arn = np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)


[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [ ]:
arn = np.array([1,2,3,4,5,6,7],ndmin=25)
print(arn)
print(arn.ndim)


[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4 5 6 7]]]]]]]]]]]]]]]]]]]]]]]]]
25
