<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/BroadcastingNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

var1 = np.array ([1,2,3])
print(var1)

var2 = np.array ([[1],[2],[3]])
print(var2)


print(var1 + var2)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
import numpy as np

var1 = np.array ([1,2,3])
print(var1.shape)

var2 = np.array ([[1],[2],[3]])
print(var2.shape)



(3,)
(3, 1)


In [ ]:
import numpy as np

var1 = np.array ([1,2,3])
print(var1.shape)
print()
print(var1)
print()

var2 = np.array ([[1],[2],[3]])
print(var2.shape)
print()
print(var2)
print()



(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]



In [ ]:
import numpy as np

var1 = np.array ([1,2,3])
print(var1.shape)
print()
print(var1)
print()

var2 = np.array ([[1],[2],[3]])
print(var2.shape)
print()
print(var2)
print()

var3 = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(var3.shape)
print()
print(var3)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

(3, 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

var1 = np.array ([1,2,3])
print(var1.shape)
print()
print(var1)
print()

var2 = np.array ([[1],[2],[3]])
print(var2.shape)
print()
print(var2)
print()

print(var1 + var2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
x = np.array ([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)

print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = 10

print(a + b)

[11 12 13]


In [ ]:
a = np.array([1, 2, 3])
print(a + 5)

[6 7 8]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr + 33)

[43 53 63 73]


In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6]])          # 2D array

b = np.array([10, 20, 30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [ ]:
a = np.array([ [1, 2, 3],[4, 5, 6]])          # column array

b = np.array([[10],[20]])

print(a + b)

[[11 12 13]
 [24 25 26]]


In [ ]:
import numpy as np               # with multiplication

a = np.array([[1, 2, 3],[4, 5, 6]])

b = np.array([10, 20, 30])

print(a * b)

[[ 10  40  90]
 [ 40 100 180]]


In [ ]:
a = np.array([[10, 20, 30],[40, 50, 60]])            #with Subtraction

b = np.array([1, 2, 3])

print(a - b)

[[ 9 18 27]
 [39 48 57]]


In [ ]:
a = np.array([[10, 20, 30],[40, 50, 60]])               # with division

b = np.array([10, 10, 10])

print(a / b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
arr = np.array([1, 2, 3, 4])               # with scalar

print(arr * 2)

[2 4 6 8]
