<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

var = np.array([9,8,7,6])
#               0,1,2,3
#               -4,-3,-2,-1

print(var[1])
print(var[-4])

8
9


In [5]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1)

[[9 8 7]
 [4 5 6]]
2

[[9 8 7]
 [4 5 6]]


In [6]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2

7


In [11]:
var2 = np.array([[[1,2],[6,7]]])

print(var2)
print(var2.ndim)
print()

print(var2)

[[[1 2]
  [6 7]]]
3

[[[1 2]
  [6 7]]]


In [12]:
var2 = np.array([[[1,2],[6,7]]])

print(var2)
print(var2.ndim)
print()

print(var2[0,1])

[[[1 2]
  [6 7]]]
3

[6 7]


In [13]:
var2 = np.array([[[1,2],[6,7]]])

print(var2)
print(var2.ndim)
print()

print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7


In [15]:
arr = np.array([[1, 2, 3],             #2D array
                [4, 5, 6],
                [7, 8, 9]])

print(arr[0, 1])
print(arr[2, 2])
print(arr[1, 0])

2
9
4
