<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/JoinArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Join Array

In [ ]:
import numpy as np           # 1D array

var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [ ]:
vr = np.array([[1,2],[3,4]])         # 2D array
vr1 = np.array([[9,8],[7,6]])

ar = np.concatenate((vr,vr1))
print(ar)

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [ ]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])

print(vr)

[[1 2]
 [3 4]]


In [ ]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])

ar_new = np.concatenate((vr,vr1),axis=1)
print(vr)
print()
print(var1)
print()
print(ar_new)

[[1 2]
 [3 4]]

[9 8 7 6]

[[1 2 9 8]
 [3 4 7 6]]


In [ ]:
var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.stack((var,var1),axis=1)
print(ar)


[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [ ]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.stack((var_1,var_2),axis = 1)
print(a_new)


[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [ ]:
var_1 = np.array([1,2,3,4])              # Row Merge
var_2 = np.array([9,8,7,6])

a_new = np.hstack((var_1,var_2))
print(a_new)


[1 2 3 4 9 8 7 6]


In [ ]:
var_1 = np.array([1,2,3,4])              # Column Merge
var_2 = np.array([9,8,7,6])

a_new = np.vstack((var_1,var_2))
print(a_new)

[[1 2 3 4]
 [9 8 7 6]]


In [ ]:
var_1 = np.array([1,2,3,4])              # Height Merge
var_2 = np.array([9,8,7,6])

a_new = np.dstack((var_1,var_2))
print(a_new)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [ ]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.stack((var_1,var_2),axis = 0)
a_new1 = np.hstack((var_1,var_2))       # Row
a_new2 = np.vstack((var_1,var_2))       # Columns
a_new3 = np.dstack((var_1,var_2))       # Height


print(a_new)
print()
print(a_new1)
print()
print(a_new2)
print()
print(a_new3)


[[1 2 3 4]
 [9 8 7 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [ ]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.stack((var_1,var_2),axis = 1)
a_new1 = np.hstack((var_1,var_2))       # Row
a_new2 = np.vstack((var_1,var_2))       # Columns
a_new3 = np.dstack((var_1,var_2))       # Height


print(a_new)
print()
print(a_new1)
print()
print(a_new2)
print()
print(a_new3)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [ ]:
# Split Array

In [ ]:
import numpy as np      # 1D array

var = np.array ([1,2,3,4,5,6])
print(var)
ar = np.array_split(var,3)
print(ar)
print(ar[0])
print(ar[1])
print(ar[2])

[1 2 3 4 5 6]


In [ ]:
import numpy as np

var = np.array([1,2,3,5,4,6])
print(var)

ar = np.array_split(var,3)

print()
print(ar)
print(type(ar))

[1 2 3 5 4 6]

[array([1, 2]), array([3, 5]), array([4, 6])]
<class 'list'>


In [ ]:
import numpy as np

var = np.array([1,2,3,5,4,6])
print(var)

ar = np.array_split(var,3)

print()
print(ar)
print(ar[0])


[1 2 3 5 4 6]

[array([1, 2]), array([3, 5]), array([4, 6])]
[1 2]


In [ ]:
import numpy as np

var1 = np.array([[1,2],[3,5],[4,6]])
print(var)

ar1 = np.array_split(var1,3)

print()
print(ar1)

[1 2 3 5 4 6]

[array([[1, 2]]), array([[3, 5]]), array([[4, 6]])]


In [ ]:
import numpy as np

var1 = np.array([[1,2],[3,5],[4,6]])
print(var)

ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3,axis=1)

print()
print(ar1)
print()
print(ar2)

[1 2 3 5 4 6]

[array([[1, 2]]), array([[3, 5]]), array([[4, 6]])]

[array([[1],
       [3],
       [4]]), array([[2],
       [5],
       [6]]), array([], shape=(3, 0), dtype=int64)]
