<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Numpy_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Matrix

In [ ]:
import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])

print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [ ]:
var1 = np.array([[1,2,3],[1,2,3]])

print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])
var2 = np.matrix([[1,2,3],[1,2,3]])

print(var)
print(type(var))
print()
print(var+var2)

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[2 4 6]
 [2 4 6]]


In [ ]:
import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])
var2 = np.matrix([[1,2,3],[1,2,3]])

print(var)
print(type(var))
print()
print(var-var2)

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np

var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])

print(var)
print(type(var))
print()
print(var*var2)

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]


In [ ]:
import numpy as np

var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])

print(var)
print(type(var))
print()
print(var*var2)
print(var.dot(var2))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]
[[3 6]
 [3 6]]


In [ ]:
var1 = np.array([[1,2,3],[1,2,3]])

print(var1)
print(type(var1))
print()
print(var1*var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]


In [ ]:
# Matrix Function

In [ ]:
import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))

print()
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))

print()
print(var.T)
print()
print(np.swapaxes(var,0,1))


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [ ]:
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
var4 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(var4)
print()
print(np.linalg.matrix_power(var4,2))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
var5 = np.matrix([[1,2,3],[1,5,5],[3,8,4]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2 3]
 [1 5 5]
 [3 8 4]]

-19.000000000000004
