<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Numpy_sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

x = np.array([[12,11,15],[21,25,20],[18,27,16]])

y = np.sort(x)
print(y)

[[11 12 15]
 [20 21 25]
 [16 18 27]]


In [ ]:
import numpy as np

x = np.array([[12,11,15],[21,25,20],[18,27,16]])

y = np.sort(x,axis=0)
print(y)

[[12 11 15]
 [18 25 16]
 [21 27 20]]


In [ ]:
import numpy as np

x = np.array([[12,11,15],[21,25,20],[18,27,16]])

y = np.argsort(x, axis=0)
print(y)

[[0 0 0]
 [2 1 2]
 [1 2 1]]


In [ ]:
import numpy as np

x = np.array([[12,11,15],[21,25,20],[18,27,16]])

y = np.argsort(x, axis=1)
print(y)

[[1 0 2]
 [2 0 1]
 [2 0 1]]


In [ ]:
import numpy as np

x = np.array([[12,11,15],[21,25,20],[18,27,16]])

x.sort()
print(x)

[[11 12 15]
 [20 21 25]
 [16 18 27]]


In [ ]:
import numpy as np         #1D array

x = np.array([2,3,4,5,6])

y = np.sort(x)
print(x)

[2 3 4 5 6]


In [ ]:
import numpy as np         #1D array

x = np.array([2,3,8,5,6])

y = np.sort(x)[::-1]
print(y)

[8 6 5 3 2]


In [ ]:
import numpy as np         #1D array

x = np.array([7,3,5,9,6])             # arrang the elemrnt in assending order
                                       # 3,5,6,7,9
                                                # 7,3,5,9,6
y = np.argsort(x)                       #indexing 0,1,2,3,4
print(y)

[1 2 4 0 3]
