<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/NumpyFunction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np          #zero arrays
ar_zero = np.zeros(4)

print(ar_zero)

[0. 0. 0. 0.]


In [ ]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Ones

In [ ]:
ar_ones = np.ones(4)
print(ar_ones)

[1. 1. 1. 1.]


In [ ]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [ ]:
# Empty

In [ ]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [ ]:
np.empty(5)   # Values are not initialized
np.zeros(5)   # All values are 0
np.ones(5)    # All values are 1

array([1., 1., 1., 1., 1.])

In [ ]:
import numpy as np      # 2D Empty Array

a = np.empty((2, 3))

print(a)

[[ 3.67175433e-315  0.00000000e+000 -2.14230552e-103]
 [ 4.04042616e-027  1.60828909e-065 -4.40786523e-215]]


In [ ]:
# Range

In [ ]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [ ]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Diagonal

In [ ]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
# Linspace

In [ ]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
