<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Random

In [ ]:
# Rand()

In [ ]:
import numpy as np

var = np.random.rand(4)
print(var)

[0.35086618 0.76202014 0.61614302 0.54768572]


In [ ]:
var1 = np.random.rand(2, 5)
print(var1)

[[0.86581982 0.18749352 0.44956392 0.87393686 0.27643948]
 [0.94993144 0.77589932 0.56974246 0.62078616 0.91281265]]


In [ ]:
# Randn()

In [ ]:
var2 = np.random.randn(5)

print(var2)

[ 0.73510746  0.73190167  0.78853013  0.59969116 -0.28230302]


In [ ]:
# Ranf()

In [ ]:
var3 = np.random.ranf(4)

print(var3)

[0.70146327 0.24031752 0.67163595 0.24552787]


In [ ]:
# Randint()

In [ ]:
var4 = np.random.randint(5, 20, 5)     #(min,max,total_values)

print(var4)

[13  7 14 16  8]


In [ ]:
 # Data Type

In [ ]:
import numpy as np

var = np.array([1, 2, 3, 4, 12, 13, 14, 15])

print("Data Type: ", var.dtype)

Data Type:  int64


In [ ]:
import numpy as np

var = np.array([1.0,1.2,1.3])

print("Data Type: ", var.dtype)

Data Type:  float64


In [ ]:
var = np.array(["a","w","r"])

print("Data Type: ", var.dtype)

Data Type:  <U1


In [ ]:
var = np.array(["a","w","r",1,2,3,4,5])

print("Data Type: ", var.dtype)

Data Type:  <U21


In [ ]:
x = np.array([1,2,3,4,5], dtype=np.int8)

print("Data Type: ", x.dtype)

Data Type:  int8


In [ ]:
x = np.array([1,2,3,4])

print("Data Type: ", x.dtype)

Data Type:  int64


In [ ]:
x = np.array([1,2,3,4,5], dtype=np.int8)

print("Data Type: ", x.dtype)
print(x)

Data Type:  int8
[1 2 3 4 5]


In [ ]:
x1 = np.array([1,2,3,4,5], dtype="f")

print("Data Type: ", x1.dtype)
print(x1)

Data Type:  float32
[1. 2. 3. 4. 5.]


In [ ]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)

print("Data Type: ", x2.dtype)
print("Data Type: ", new.dtype)
print(x2)
print(new)

Data Type:  int64
Data Type:  float32
[1 2 3 4]


In [ ]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)

new_one = np.int_(new)
print("Data Type: ", x2.dtype)
print("Data Type: ", new.dtype)
print("Data Type: ", new_one.dtype)


print(x2)
print(new)
print(new_one)

Data Type:  int64
Data Type:  float32
Data Type:  int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [ ]:
 x3 = np.array([1,2,3,4])

 new_1 = x3.astype(float)

 print(x3)
 print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
x4 = np.array([1,2,3,4])

new_2 = x4.astype(float)

print(new_2.dtype)
print(x4.dtype)
print(x4)
print(new_2)

float64
int64
[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
# Arithmetic operation

In [ ]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var + 3

print(varadd)

[4 5 6 7]


In [ ]:
var1 = np.array([1,2,3,4])         # add to var.
var2 = np.array([1,2,3,4])

varadd = var1 + var2

print(varadd)

[2 4 6 8]


In [ ]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,3)

print(varadd)

[4 5 6 7]


In [ ]:
var = np.array([1,2,3,4])

varadd = var - 3

print(varadd)

[-2 -1  0  1]


In [ ]:
var = np.array([1,2,3,4])

varadd = var * 3

print(varadd)

[ 3  6  9 12]


In [ ]:
var = np.array([1,2,3,4])

varadd = var % 3

print(varadd)

[1 2 0 1]


In [ ]:
var = np.array([1,2,3,4])

varadd = var / 3

print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [ ]:
var = np.array([1,2,3,4])

varadd = var ** 3

print(varadd)

[ 1  8 27 64]


In [ ]:
var = np.array([1,2,3,4])

varadd = np.reciprocal(var)

print(varadd)

[1 0 0 0]


In [ ]:
# 2D Array

In [ ]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

varadd = var21 + var22

print(varadd)

[[2 4 6 8]
 [2 4 6 8]]


In [ ]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd = var21 + var22

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [ ]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd = var21 * var22

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [ ]:
# Arithmetic Function

In [ ]:
import numpy as np

var = np.array([1,2,3,4,5,3,2])

print("min :",np.min(var))
print("max :",np.max(var))

min : 1
max : 5


In [ ]:
import numpy as np

var = np.array([1,2,3,4,5,3,2])

print("min :",np.min(var),np.argmin(var))
print("max :",np.max(var),np.argmax(var))

min : 1 0
max : 5 4


In [ ]:
import numpy as np

var = np.array([1,2,3,4,5,3,2])

print("min :",np.min(var))
print("max :",np.max(var))
print("argmin :",np.argmin(var))
print("argmax :",np.argmax(var))
print("sqrt :",np.sqrt(var))


min : 1
max : 5
argmin : 0
argmax : 4
sqrt : [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [ ]:
var1 = np.array([[1,2,3],[9,5,6]])

print(np.min(var1,axis=0))

[1 2 3]


In [ ]:
var1 = np.array([[1,2,3],[9,5,6]])

print(np.min(var1,axis=1))

[1 5]


In [ ]:
var1 = np.array([[1,2,3],[9,5,6]])

print(np.max(var1,axis=0))

[9 5 6]


In [ ]:
var1 = np.array([[1,2,3],[9,5,6]])

print(np.min(var1,axis=1))

[1 5]


In [ ]:
var2 = np.array([1,2,3])

print(np.sin(var2))

[0.84147098 0.90929743 0.14112001]


In [ ]:
var2 = np.array([1,2,3])

print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


In [ ]:
var2 = np.array([1,2,3,5,6])


print(np.cumsum(var2))

[ 1  3  6 11 17]


In [1]:
import numpy as np

x = np.array([4,2,3,9,7])
y = np.max(x)

print(y)

9
