<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Shape%26Reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Shape

In [ ]:
import numpy as np

var = np.array([[1,2],[1,2]])

print(var)

[[1 2]
 [1 2]]


In [ ]:
import numpy as np

var = np.array([[1,2],[1,2]])

print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [ ]:
import numpy as np

var = np.array([[1,2,3,4],[1,2,3,4]])

print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [ ]:
var1 = np.array([1,2,3,4], ndmin=4)

print(var1)
print()
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]

4

(1, 1, 1, 4)


In [ ]:
import numpy as np

a = np.arange(1, 13)

print(a)
print(a.shape)

b = a.reshape(3, 4)

print(b)
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
# Reshaping

In [ ]:
var2 = np.array([1,2,3,4,5,6])         # 2-Dimension array

x = var2.reshape(3,2)

print(x)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
var2 = np.array([1,2,3,4,5,6])
print(var2)

print()

x = var2.reshape(3,2)

print(x)

[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)

print()

x = var2.reshape(3,2)

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)

print()

x = var2.reshape(3,2)     # 2-Dimension array

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)

print()

x1 = var3.reshape(2,3,2)       # 3-Dimension array

print(x1)
print(x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [ ]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)

print()

x1 = var3.reshape(2,3,2)      # 3-Dimension array

print(x1)
print(x1.ndim)

print()

one = x1.reshape(-1)       # 1-Dimension array(reshap)

print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

b = a.reshape(2, 3)

print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b = a.reshape(2, 3)

print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
import numpy as np

a = np.arange(1, 13)

b = a.reshape(3, -1)

print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np           # 2D to 1D

a = np.array([[1, 2, 3], [4, 5, 6]])

b = a.reshape(6)

print(b)

[1 2 3 4 5 6]


In [ ]:
import numpy as np              # 1D to 3D

a = np.arange(1, 9)

b = a.reshape(2, 2, 2)

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
 # Important NumPy Attributes Related to Shape

In [ ]:
# a.shape
# a.ndim
# a.size
# a.dtype

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],[4, 5, 6]])

print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Size:", a.size)
print("Data type:", a.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64
