<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

var = np.array([1,2,3,4,5,6,7])
#               0,1,2,3,4,5,6

print(var)

print()

print("2 to 5 :",var[1:5])


[1 2 3 4 5 6 7]

2 to 5 : [2 3 4 5]


In [ ]:
import numpy as np

var = np.array([1,2,3,4,5,6,7])
#               0,1,2,3,4,5,6

print(var)

print()

print("2 to 5 :",var[1:5])

print("2 to End :",var[1:])

[1 2 3 4 5 6 7]

2 to 5 : [2 3 4 5]
2 to End : [2 3 4 5 6 7]


In [ ]:
import numpy as np

var = np.array([1,2,3,4,5,6,7])
#               0,1,2,3,4,5,6

print(var)

print()

print("2 to 5 :",var[1:5])

print("2 to End :",var[1:])

print("Start to 5 :",var[:5])

[1 2 3 4 5 6 7]

2 to 5 : [2 3 4 5]
2 to End : [2 3 4 5 6 7]
Start to 5 : [1 2 3 4 5]


In [ ]:
import numpy as np

var = np.array([1,2,3,4,5,6,7])
#               0,1,2,3,4,5,6

print(var)

print()

print("2 to 5 :",var[1:5])

print("2 to End :",var[1:])

print("Start to 5 :",var[:5])

print("stop : ",var[::])

[1 2 3 4 5 6 7]

2 to 5 : [2 3 4 5]
2 to End : [2 3 4 5 6 7]
Start to 5 : [1 2 3 4 5]
stop :  [1 2 3 4 5 6 7]


In [ ]:
import numpy as np

var = np.array([9,8,7,6,5,4,3])
#               0,1,2,3,4,5,6

print(var)

print()

print("2 to 5 :",var[1:5])

print("2 to End :",var[1:])

print("Start to 5 :",var[:5])

print("stop : ",var[::2])

[9 8 7 6 5 4 3]

2 to 5 : [8 7 6 5]
2 to End : [8 7 6 5 4 3]
Start to 5 : [9 8 7 6 5]
stop :  [9 7 5 3]


In [ ]:
import numpy as np

var = np.array([9,8,7,6,5,4,3])
#               0,1,2,3,4,5,6

print(var)

print()

print("2 to 5 :",var[1:5])

print("2 to End :",var[1:])

print("Start to 5 :",var[:5])

print("stop : ",var[1:5:2])

[9 8 7 6 5 4 3]

2 to 5 : [8 7 6 5]
2 to End : [8 7 6 5 4 3]
Start to 5 : [9 8 7 6 5]
stop :  [8 6]


In [ ]:
import numpy as np

var1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])


print(var1)
print()

print("2 to 5: ",var1[1,1:4])

print("8 to 5: ",var1[1,1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

2 to 5:  [7 8 9]
8 to 5:  [ 7  8  9 10]


In [ ]:
import numpy as np                  #2D array

array1 = np.array([[15,16,17],[25,26,27],[35,36,37],[45,46,47]])

print(array1[1,])
print(array1[:,1])
print(array1[1:3,1:3])
print(array1[1:3, ])
print(array1[: ,1:3])
print(array1[1:3,1])
print(array1[1:3,:1])

[25 26 27]
[16 26 36 46]
[[26 27]
 [36 37]]
[[25 26 27]
 [35 36 37]]
[[16 17]
 [26 27]
 [36 37]
 [46 47]]
[26 36]
[[25]
 [35]]
